package Utils;


import org.apache.log4j.*;

public class Log {

    public static Logger log = Logger.getLogger(Log.class.getName());

    //when the test start , I should print the logs
    // when my test stops i should print the logs
    // if i want to print any message in between i should print the logs

    public static void startTestCase(String testCaseName){
        log.info("$$$$$$$$$$$$$$$$$$$");
        log.info("$$$$$$$$$$$$$$$$$$$");
        log.info("$$$$$$$$"+testCaseName+"$$$$$$$$$$$$$");
    }
    public static void  endTestCase(String testCaseName){
        log.info("*************");
        log.info("*************");
        log.info("*************"+testCaseName+"*************");
    }
    public static void info(String message){

        log.info(message);
    }
    public static void warning(String warning){
        log.info(warning);
    }

    //MAVEN lifeCycle

    //maven life cycle: this consists of several phase
    // clean: removes all the files generated by the previous build for the use of clean
    // validate: check the project is correct and all the necessary information is available
    // compile: compiles the source code of the project
    // test: runs the tests for the project
    // package: packages the complied code into a distributed format such as JAR or WAR files
    // verify: it run and checks on results of integration test to ensure quality criteria is met
    // install: installs the packages into local repository
    //site: generates documentation for the project
    // deploy: copies the final package to remote repository for sharing with others developers

}